name: Build
on: [push, pull_request]

jobs:
 # Build job. Builds app for Android with Buildozer
  build-android:
 name: Food-Diary
    runs-on: ubuntu-latest

    steps:
 - name: Checkout
        uses: actions/checkout@v2

 - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
 workdir: test_app
          buildozer_version: stable

 - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
 name: 
          packagepath: ${{ steps.buildozer.outputs.filename }}
